title: "Ankit Jaiswal"
email: "ankitjaiswal.584@gmail.com"
linkedin: "/ankitjaiswal.584"
github: "https://github.com/ankitjaiswal584"
description: "MA Development Studies (TISS) | Former JRF (AIIMS Bhopal) â€” Exploring data-driven approaches in social research and development."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ankitjaiswal584.github.io" # the base hostname & protocol for your site
theme: minima
plugins:
  - jekyll-feed
